# build environment
FROM node:12.18.0-alpine as build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
ENV NODE_ENV production
RUN npm ci --silent
RUN apk --no-cache add g++ gcc libgcc libstdc++ linux-headers make python git fts-dev
RUN sudo npm parcel@2.3.1
COPY ./ ./
RUN npm run build

# serve environment
FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 50102
CMD ["nginx", "-g", "daemon off;"]
